"""Non-biotech DMV employers worth watching, plus curated student programs.

The BioPharmGuy directory only covers life sciences. This file adds the other
half of the DMV job market a computational/AI-leaning engineering student
actually applies to: national labs, FFRDCs, defense primes, health systems,
universities and the big local tech employers.

`ats` is an optional hint. Discovery validates every hint against the live
board and drops it if it 404s, so a wrong guess here is harmless.
"""

from __future__ import annotations

from .models import Company

_MAJOR: list[dict] = [
    # --- Federal labs, agencies and FFRDCs ---
    {"name": "NIST", "domain": "nist.gov", "city": "Gaithersburg", "state": "MD",
     "category": "National metrology lab; SURF undergraduate research program", "tier": "research_institution"},
    {"name": "National Institutes of Health", "domain": "nih.gov", "city": "Bethesda", "state": "MD",
     "category": "Biomedical research; Summer Internship Program", "tier": "research_institution"},
    {"name": "FDA", "domain": "fda.gov", "city": "Silver Spring", "state": "MD",
     "category": "Regulatory science, computational toxicology", "tier": "research_institution"},
    {"name": "NASA Goddard Space Flight Center", "domain": "nasa.gov", "city": "Greenbelt", "state": "MD",
     "category": "OSTEM internships, data science and modeling", "tier": "research_institution"},
    {"name": "Army Research Laboratory (DEVCOM)", "domain": "arl.army.mil", "city": "Adelphi", "state": "MD",
     "category": "AI/ML and biotechnology research; SEAP/CQL programs", "tier": "research_institution"},
    {"name": "Johns Hopkins Applied Physics Laboratory", "domain": "jhuapl.edu", "city": "Laurel", "state": "MD",
     "category": "University-affiliated research center; large intern program", "tier": "research_institution"},
    {"name": "MITRE", "domain": "mitre.org", "city": "McLean", "state": "VA",
     "category": "FFRDC; health informatics and AI research", "tier": "research_institution"},
    {"name": "HHMI Janelia Research Campus", "domain": "janelia.org", "city": "Ashburn", "state": "VA",
     "category": "Computational neuroscience and imaging research", "tier": "research_institution"},
    {"name": "J. Craig Venter Institute", "domain": "jcvi.org", "city": "Rockville", "state": "MD",
     "category": "Genomics and bioinformatics research", "tier": "research_institution"},
    {"name": "Institute for Defense Analyses", "domain": "ida.org", "city": "Alexandria", "state": "VA",
     "category": "FFRDC; quantitative analysis", "tier": "research_institution"},
    {"name": "CNA", "domain": "cna.org", "city": "Arlington", "state": "VA",
     "category": "Research and analysis; data science internships", "tier": "research_institution"},
    {"name": "Noblis", "domain": "noblis.org", "city": "Reston", "state": "VA",
     "category": "Nonprofit science and technology; bioinformatics", "tier": "research_institution"},
    {"name": "RAND Corporation", "domain": "rand.org", "city": "Arlington", "state": "VA",
     "category": "Policy research; quantitative analysis", "tier": "research_institution"},

    # --- Defense / government services ---
    {"name": "Leidos", "domain": "leidos.com", "city": "Reston", "state": "VA",
     "category": "Defense and health IT; large intern program", "tier": "major_employer"},
    {"name": "Booz Allen Hamilton", "domain": "boozallen.com", "city": "McLean", "state": "VA",
     "category": "Consulting; AI/ML and data science practice", "tier": "major_employer"},
    {"name": "CACI International", "domain": "caci.com", "city": "Reston", "state": "VA",
     "category": "Defense technology and analytics", "tier": "major_employer"},
    {"name": "SAIC", "domain": "saic.com", "city": "Reston", "state": "VA",
     "category": "Government IT and engineering services", "tier": "major_employer"},
    {"name": "Peraton", "domain": "peraton.com", "city": "Herndon", "state": "VA",
     "category": "National security technology", "tier": "major_employer"},
    {"name": "ManTech", "domain": "mantech.com", "city": "Herndon", "state": "VA",
     "category": "Defense IT and cyber", "tier": "major_employer"},
    {"name": "General Dynamics Information Technology", "domain": "gdit.com", "city": "Falls Church", "state": "VA",
     "category": "Government IT, health and biodefense programs", "tier": "major_employer"},
    {"name": "Lockheed Martin", "domain": "lockheedmartin.com", "city": "Bethesda", "state": "MD",
     "category": "Aerospace and defense; large college program", "tier": "major_employer"},
    {"name": "Northrop Grumman", "domain": "northropgrumman.com", "city": "Falls Church", "state": "VA",
     "category": "Aerospace and defense; Linthicum MD engineering site", "tier": "major_employer"},
    {"name": "BAE Systems", "domain": "baesystems.com", "city": "Arlington", "state": "VA",
     "category": "Defense electronics", "tier": "major_employer"},
    {"name": "Parsons", "domain": "parsons.com", "city": "Chantilly", "state": "VA",
     "category": "Defense and infrastructure technology", "tier": "major_employer"},
    {"name": "Amentum", "domain": "amentum.com", "city": "Chantilly", "state": "VA",
     "category": "Engineering and technical services", "tier": "major_employer"},
    {"name": "Two Six Technologies", "domain": "twosixtech.com", "city": "Arlington", "state": "VA",
     "category": "National security R&D", "tier": "major_employer"},
    {"name": "Applied Insight", "domain": "appliedinsight.com", "city": "Tysons", "state": "VA",
     "category": "Cloud and data engineering for government", "tier": "major_employer"},

    # --- Tech and finance ---
    {"name": "Amazon / AWS", "domain": "amazon.jobs", "city": "Arlington", "state": "VA",
     "category": "HQ2; SDE and applied science internships", "tier": "major_employer"},
    {"name": "Microsoft", "domain": "microsoft.com", "city": "Reston", "state": "VA",
     "category": "Federal and Azure engineering", "tier": "major_employer"},
    {"name": "Google", "domain": "google.com", "city": "Reston", "state": "VA",
     "category": "Cloud and public sector engineering", "tier": "major_employer"},
    {"name": "Capital One", "domain": "capitalone.com", "city": "McLean", "state": "VA",
     "category": "Tech internships; ML and data science", "tier": "major_employer"},
    {"name": "Fannie Mae", "domain": "fanniemae.com", "city": "Washington", "state": "DC",
     "category": "Technology and analytics internships", "tier": "major_employer"},
    {"name": "Freddie Mac", "domain": "freddiemac.com", "city": "McLean", "state": "VA",
     "category": "Technology and modeling internships", "tier": "major_employer"},
    {"name": "T. Rowe Price", "domain": "troweprice.com", "city": "Baltimore", "state": "MD",
     "category": "Technology and quantitative internships", "tier": "major_employer"},
    {"name": "Appian", "domain": "appian.com", "city": "McLean", "state": "VA",
     "category": "Enterprise software", "tier": "major_employer"},
    {"name": "Cvent", "domain": "cvent.com", "city": "Tysons", "state": "VA",
     "category": "Event technology software", "tier": "major_employer"},
    {"name": "Verisign", "domain": "verisign.com", "city": "Reston", "state": "VA",
     "category": "Internet infrastructure", "tier": "major_employer"},
    {"name": "Danaher", "domain": "danaher.com", "city": "Washington", "state": "DC",
     "category": "Life sciences and diagnostics conglomerate", "tier": "major_employer"},
    {"name": "Under Armour", "domain": "underarmour.com", "city": "Baltimore", "state": "MD",
     "category": "Consumer tech, data science, sports science", "tier": "major_employer"},
    {"name": "Marriott International", "domain": "marriott.com", "city": "Bethesda", "state": "MD",
     "category": "Technology and analytics internships", "tier": "major_employer"},

    # --- Health systems and payers ---
    {"name": "Johns Hopkins Medicine", "domain": "jhu.edu", "city": "Baltimore", "state": "MD",
     "category": "Academic medical center; biomedical informatics", "tier": "research_institution"},
    {"name": "University of Maryland", "domain": "umd.edu", "city": "College Park", "state": "MD",
     "category": "Campus research and student positions", "tier": "research_institution"},
    {"name": "University of Maryland Baltimore", "domain": "umaryland.edu", "city": "Baltimore", "state": "MD",
     "category": "Institute for Genome Sciences and medical school labs", "tier": "research_institution"},
    {"name": "UMBC", "domain": "umbc.edu", "city": "Baltimore", "state": "MD",
     "category": "Campus research and student positions", "tier": "research_institution"},
    {"name": "Georgetown University", "domain": "georgetown.edu", "city": "Washington", "state": "DC",
     "category": "Biomedical informatics and campus research", "tier": "research_institution"},
    {"name": "George Washington University", "domain": "gwu.edu", "city": "Washington", "state": "DC",
     "category": "Campus research and student positions", "tier": "research_institution"},
    {"name": "MedStar Health", "domain": "medstarhealth.org", "city": "Columbia", "state": "MD",
     "category": "Health system; clinical analytics", "tier": "major_employer"},
    {"name": "Inova Health System", "domain": "inova.org", "city": "Falls Church", "state": "VA",
     "category": "Health system; Schar Cancer Institute, genomics", "tier": "major_employer"},
    {"name": "Children's National Hospital", "domain": "childrensnational.org", "city": "Washington", "state": "DC",
     "category": "Pediatric research and medical imaging AI", "tier": "research_institution"},
    {"name": "CareFirst BlueCross BlueShield", "domain": "carefirst.com", "city": "Baltimore", "state": "MD",
     "category": "Health insurer; data and analytics internships", "tier": "major_employer"},
    {"name": "Kaiser Permanente", "domain": "kaiserpermanente.org", "city": "Rockville", "state": "MD",
     "category": "Integrated health system; research division", "tier": "major_employer"},
    {"name": "Aledade", "domain": "aledade.com", "city": "Bethesda", "state": "MD",
     "category": "Value-based care analytics", "tier": "major_employer"},
    {"name": "Arcadia", "domain": "arcadia.io", "city": "Washington", "state": "DC",
     "category": "Healthcare data platform", "tier": "major_employer"},
]

# High-value programs that are not on any scrapable job board. These are shown
# as a separate panel on the site so they are never forgotten at deadline time.
PROGRAMS: list[dict] = [
    {"name": "NIST SURF (Summer Undergraduate Research Fellowship)",
     "org": "NIST", "location": "Gaithersburg, MD",
     "url": "https://www.nist.gov/surf",
     "window": "Applications typically open Oct, close late Jan/Feb",
     "note": "Paid 11-week research fellowship. Strong fit for computational and data-heavy projects."},
    {"name": "NIH Summer Internship Program (SIP)",
     "org": "National Institutes of Health", "location": "Bethesda, MD",
     "url": "https://www.training.nih.gov/programs/sip",
     "window": "Opens mid-Nov, closes early Feb",
     "note": "Paid. Search the PI directory for computational biology and biomedical data science labs."},
    {"name": "NIH Postbac IRTA",
     "org": "National Institutes of Health", "location": "Bethesda, MD",
     "url": "https://www.training.nih.gov/programs/postbac_irta",
     "window": "Rolling",
     "note": "Post-graduation option; worth tracking early for a May 2028 landing."},
    {"name": "JHU Applied Physics Laboratory College Internships",
     "org": "JHU APL", "location": "Laurel, MD",
     "url": "https://www.jhuapl.edu/careers/internships",
     "window": "Postings appear Sep-Dec for the following summer",
     "note": "Requires US citizenship for most roles. Large AI/ML and biomedical portfolio."},
    {"name": "NASA OSTEM Internships",
     "org": "NASA Goddard", "location": "Greenbelt, MD",
     "url": "https://intern.nasa.gov/",
     "window": "Summer deadline typically late Feb",
     "note": "One application covers all centers. Goddard is a 40-minute drive."},
    {"name": "Army Educational Outreach (SEAP / CQL)",
     "org": "DEVCOM Army Research Laboratory", "location": "Adelphi & Aberdeen, MD",
     "url": "https://www.usaeop.com/program/cql/",
     "window": "Opens Nov, closes Feb",
     "note": "Paid apprenticeships in ARL labs, including AI and biotechnology directorates."},
    {"name": "HHMI Janelia Undergraduate Scholars",
     "org": "HHMI Janelia", "location": "Ashburn, VA",
     "url": "https://www.janelia.org/you-janelia/students-postdocs",
     "window": "Winter deadlines",
     "note": "Computational neuroscience and bioimage analysis."},
    {"name": "FDA ORISE Fellowships",
     "org": "FDA", "location": "Silver Spring, MD",
     "url": "https://orise.orau.gov/fda/",
     "window": "Rolling postings",
     "note": "Search for computational toxicology, bioinformatics and AI-in-medical-devices postings."},
    {"name": "UMD Undergraduate Research (FIRE / MERIT / BSOS)",
     "org": "University of Maryland", "location": "College Park, MD",
     "url": "https://ugresearch.umd.edu/",
     "window": "Varies by program",
     "note": "On-campus paid research; the fastest route to a first line of research experience."},
    {"name": "USAJOBS Pathways Internships",
     "org": "US Federal Government", "location": "DMV-wide",
     "url": "https://www.usajobs.gov/Search/Results?hp=student",
     "window": "Rolling",
     "note": "Covers NIST, NIH, FDA, Census, CMS, NGA and more. The scraper can pull these automatically with a free USAJOBS API key."},
]


def major_employers() -> list[Company]:
    return [Company(**d) for d in _MAJOR]
